---
- name: create user
  user:
    name: "{{ remote_user }}"
    password: "{{ remote_user_passwd }}"
    groups: "{{ remote_user_groups }}"
    append: yes
    shell: /bin/bash
  when: create_remote_user

- name: add authorized key
  authorized_key:
    user: "{{ remote_user }}"
    key: "{{ lookup('file', '~/'+ssh_key_file+'.pub') }}"
